### ISSUE TITLE
Terminar grilla

### ISSUE THREAD

**Issue by CristobalM** [DCC-CC4401/2018-1-Winning-Eleven-11-T4#10]
Necesario para varios requisitos

**Comment by Vokturz** [comment]
Grilla cambiada por la de [FullCalendar.io](https://fullcalendar.io/), por ahora se pueden solicitar reservas desde la landing page de personas naturales

**Comment by Vokturz** [comment]
Requisitos que cumple la grilla a la fecha:

- **Requisitos generales:** 6, 13 (falta especificar cuando es quincho y cuando no)
- **LP personas naturales:** 19, 20, 21, 22
- **Ficha de un Espacio:**  43, 44. Sobre la implementación en la ficha, notificarme cuando se requiera agregar.
- **LP Administradores:** 52, 53
